{% set name = "psdm_qs_cli" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c2d3c45363c985f40fee0555ba2011301a0cabdf5fa3a8d95bb53b0623e879b8

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  entry_points:
    - QSGenerateExcelSpreadSheet.py = psdm_qs_cli.QSGenerateExcelSpreadSheet:main
    - QSGenerateJSON.py = psdm_qs_cli.QSGenerateJSON:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - krtc
    - six
    - requests
    - openpyxl

test:
  imports:
    - psdm_qs_cli
  commands:
    - QSGenerateExcelSpreadSheet.py --help
    - QSGenerateJSON.py --help

about:
  home: https://github.com/pcdshub/psdm_qs_cli
  dev_url: https://github.com/pcdshub/psdm_qs_cli
  summary: |
     Python clients for interacting with SLAC National Accelerator Laboratory's
     PCDS LCLS experimental questionnaire
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - klauer
    - zrylettc
    - zllentz
