{% set name = "psdm_qs_cli" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: de718418e1e6b1d9e7322e4a729ea76f9a52de0648be59ccc60a2fee34b9fd71

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - QSGenerateExcelSpreadSheet.py = psdm_qs_cli.QSGenerateExcelSpreadSheet:main
    - QSGenerateJSON.py = psdm_qs_cli.QSGenerateJSON:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - krtc
    - six
    - requests
    - openpyxl

test:
  imports:
    - psdm_qs_cli
  commands:
    - QSGenerateExcelSpreadSheet.py --help
    - QSGenerateJSON.py --help

about:
  home: https://github.com/pcdshub/psdm_qs_cli
  dev_url: https://github.com/pcdshub/psdm_qs_cli
  summary: |
    Python clients for interacting with SLAC National Accelerator Laboratory's
    PCDS LCLS experimental questionnaire
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - klauer
    - tangkong
    - zrylettc
    - zllentz
