{% set name = "psdm_qs_cli" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f210948ac8a61c491ff33d0111486fb220bd8f4befaddbfff42aa776b3916916

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - QSGenerateExcelSpreadSheet.py = psdm_qs_cli.QSGenerateExcelSpreadSheet:main
    - QSGenerateJSON.py = psdm_qs_cli.QSGenerateJSON:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - krtc
    - openpyxl
    - requests

test:
  imports:
    - psdm_qs_cli
  commands:
    - QSGenerateExcelSpreadSheet.py --help
    - QSGenerateJSON.py --help

about:
  home: https://github.com/pcdshub/psdm_qs_cli
  dev_url: https://github.com/pcdshub/psdm_qs_cli
  summary: |
    Python clients for interacting with SLAC National Accelerator Laboratory's
    PCDS LCLS experimental questionnaire
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - klauer
    - tangkong
    - zllentz
